### ISSUE TITLE
Create populated 3D model & .step file of open core board

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Open-Core-M5stack#3]
Would be good to get a 3D model with the headers/UEXT/[Grove?](https://github.com/rosmo-robot/Open-Core-M5stack/issues/5) & ESP32devCv4 board as 3D parts. The board should be white, with black silkscreen & including version number 0.1v on the silkscreen. To then export this to Online viewers 

& create .STEP file to enable https://github.com/rosmo-robot/Rosmo_3D/issues/4

**Comment by ShouravSarkar** [comment]
yes. It is possible to do that. but it will cost some more design cost also

**Comment by samuk** [comment]
Ok, no worries.
