### ISSUE TITLE
V2 ESP32 dev board compatible with; M5stack, Stemma, OLED

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Open-Core-M5stack#4]
The latest version of this research moved [here](https://github.com/rosmo-robot/Open-Core-M5stack/blob/main/v2/readme.md)

<img width="370" alt="opencoreesp32" src="https://user-images.githubusercontent.com/400875/151476227-865af0c9-5c3e-4b6e-902d-47326b499fff.png">
<img width="351" alt="opencore" src="https://user-images.githubusercontent.com/400875/151476250-7e076ac4-c0a4-49d5-80a2-1c5199740953.png">

<img width="489" alt="side" src="https://user-images.githubusercontent.com/400875/151074421-d22a6a05-58cb-4bdc-bd93-8d7e2470e1fe.png">

<img width="184" alt="otto5" src="https://user-images.githubusercontent.com/400875/150679018-b0bb5ad0-db5d-4c06-ad89-1fea6cc3b11b.png">

Very rough sketch of CERN licenced [ESP32 board](https://easyeda.com/editor#id=0c94645e6c4e443cb9d172e18162d7fa) in 5cm x 5cm M5stack dimensions.

- 8x servo for a walking otto as [Robo8080 documents](https://togetter.com/li/1374900) 
- 5v input via JST
-  Optional [HCS404](https://github.com/rosmo-robot/Rosmo_3D/issues/6) staggered pins
- Optional [M5 Mbus](https://forum.m5stack.com/topic/360/m5stack-fire-pinout-leaflet)
- Optional [ staggered 7pin display 1.44](https://www.aliexpress.com/item/1005001636544551.html)
- Optional [3v Stemma](https://www.tomshardware.com/features/stemma-vs-qwiic-vs-grove-connectors) Supports [Qwiic](https://www.reddit.com/r/electronics/comments/8lhxwg/sparkfuns_qwiic_standard_for_modular_i2c_devices/), [Grove (I2C)](https://thepihut.com/products/qwiic-cable-grove-adapter-100mm) ,[Gravity](https://learn.adafruit.com/introducing-adafruit-stemma-qt/dfrobot-gravity)

**Use cases might include:**

**Rosmo**
https://rosmo.io

**Rosmo with micro servo** 
Driven just by Open Core and [ 2x continuous rotation micro servo](https://kitronik.co.uk/products/2589-fs90r-360-degree-continuous-rotation-servo) instead of BLDC. These could fit in the existing BLDC socket with a 3d printed adaptor

**Otto DIY**
![ottodiy_instructionmanual_v09-13_uhdZdIQYm5](https://user-images.githubusercontent.com/400875/148856089-a5630a26-f447-49af-9f35-735d87427f64.jpg)

Otto Ninja is 4cm x 4cm internally 

**Notes**
Nice ['snap' proto board here](https://twitter.com/CRImierTech/status/1481676889353773059)

Breakout garden [style pins](https://www.aliexpress.com/item/1005003003362076.html)

**1.44" & 1.8 Sureno fit in footprint ST7735  https://www.aliexpress.com/item/32913241143.html  [supported](https://github.com/Bodmer/TFT_eSPI)**  29.70x43.36(mm) http://www.lcdwiki.com/1.44inch_SPI_Module_ST7735S_SKU:MSP1443
<html>
<body>

1 | VCC | 5V/3.3V power input
-- | -- | --
2 | GND | Ground
3 | CS | LCD chip select signal, low level enable
4 | RESET | LCD reset signal, low level reset
5 | A0 | LCD register / data selection signal,high level: register, low level: data
6 | SDA | SPI bus write data signal
7 | SCK | SPI bus clock signal
8 | LED | Backlight control, high level lighting,if not controlled, connect 3.3V always bright

</body>
</html>

**Comment by runger1101001** [comment]
In my mind, this mixes up different concepts:

- in m5 stack, there are cores and modules. the open-core is a core, but the servo and sonar stuff should be on a module.
- on the other hand if you want a minimal cost board for robots, then we could drop the m5 stack support (which complicates things and costs $$$) and make a specific board for that. But honestly I see this niche well served by a huge host of cheap boards available on AliExpress, see designs like Osmo, Zerobot etc...

Putting it all together runs the risk of producing some kind of franken-core, not properly compatible with m5 concepts, but also not ideal as a basic robot board

**Comment by samuk** [comment]
I take your point.

It's driven by interest from @ottodiy. If we can support their use case well then they might help with the distribution/ development of the board. I guess I hope it could be a board that sees you through a robotics journey 

1) Get a Rosmo/ Otto wheeled moving about on continuous micro servo & Blockly
2) Invest a bit more & make a walking Otto
3) invest a bit more and plug in some grove stuff
4) Invest a bit more and add an official M5 stack motor driver 
5) Invest a bit more Add a RosmoESC(s) to give better motor control
6) Invest a bit more and get a proto board, do some soldering
7) Fry the board with your dodgy soldering, get a proper M5 core instead :)

**Comment by runger1101001** [comment]
Ah, I see! I'll make the observation that Ottos head looks a bit like an m5 stack in shape... :-)
